const files = [
"augmented dodecahedron.obj",
"augmented hexagonal prism.obj",
"augmented pentagonal prism.obj",
"augmented sphenocorona.obj",
"augmented triangular prism.obj",
"augmented tridiminished icosahedron.obj",
"augmented truncated cube.obj",
"augmented truncated dodecahedron.obj",
"augmented truncated tetrahedron.obj",
"biaugmented pentagonal prism.obj",
"biaugmented triangular prism.obj",
"biaugmented truncated cube.obj",
"bigyrate diminished rhombicosidodecahedron.obj",
"bilunabirotunda.obj",
"cube.obj",
"cuboctahedron.obj",
"decagonal antiprism.obj",
"decagonal prism.obj",
"diminished rhombicosidodecahedron.obj",
"disphenocingulum.obj",
"dodecahedron.obj",
"elongated pentagonal bipyramid.obj",
"elongated pentagonal cupola.obj",
"elongated pentagonal gyrobicupola.obj",
"elongated pentagonal gyrobirotunda.obj",
"elongated pentagonal gyrocupolarotunda.obj",
"elongated pentagonal orthobicupola.obj",
"elongated pentagonal orthobirotunda.obj",
"elongated pentagonal orthocupolarotunda.obj",
"elongated pentagonal pyramid.obj",
"elongated pentagonal rotunda.obj",
"elongated square bipyramid.obj",
"elongated square cupola.obj",
"elongated square gyrobicupola.obj",
"elongated square pyramid.obj",
"elongated triangular bipyramid.obj",
"elongated triangular cupola.obj",
"elongated triangular gyrobicupola.obj",
"elongated triangular orthobicupola.obj",
"elongated triangular pyramid.obj",
"gyrate bidiminished rhombicosidodecahedron.obj",
"gyrate rhombicosidodecahedron.obj",
"gyrobifastigium.obj",
"gyroelongated pentagonal bicupola.obj",
"gyroelongated pentagonal birotunda.obj",
"gyroelongated pentagonal cupola.obj",
"gyroelongated pentagonal cupolarotunda.obj",
"gyroelongated pentagonal pyramid.obj",
"gyroelongated pentagonal rotunda.obj",
"gyroelongated square bicupola.obj",
"gyroelongated square bipyramid.obj",
"gyroelongated square cupola.obj",
"gyroelongated square pyramid.obj",
"gyroelongated triangular bicupola.obj",
"gyroelongated triangular cupola.obj",
"hebesphenomegacorona.obj",
"hexagonal antiprism.obj",
"hexagonal prism.obj",
"icosahedron.obj",
"icosidodecahedron.obj",
"metabiaugmented dodecahedron.obj",
"metabiaugmented hexagonal prism.obj",
"metabiaugmented truncated dodecahedron.obj",
"metabidiminished icosahedron.obj",
"metabidiminished rhombicosidodecahedron.obj",
"metabigyrate rhombicosidodecahedron.obj",
"metagyrate diminished rhombicosidodecahedron.obj",
"octagonal antiprism.obj",
"octagonal prism.obj",
"octahedron.obj",
"parabiaugmented dodecahedron.obj",
"parabiaugmented hexagonal prism.obj",
"parabiaugmented truncated dodecahedron.obj",
"parabidiminished rhombicosidodecahedron.obj",
"parabigyrate rhombicosidodecahedron.obj",
"paragyrate diminished rhombicosidodecahedron.obj",
"pentagonal antiprism.obj",
"pentagonal bipyramid.obj",
"pentagonal cupola.obj",
"pentagonal gyrobicupola.obj",
"pentagonal gyrocupolarotunda.obj",
"pentagonal orthobicupola.obj",
"pentagonal orthobirotunda.obj",
"pentagonal orthocupolarotunda.obj",
"pentagonal prism.obj",
"pentagonal pyramid.obj",
"pentagonal rotunda.obj",
"rhombicosidodecahedron.obj",
"rhombicuboctahedron.obj",
"snub cube.obj",
"snub disphenoid.obj",
"snub dodecahedron.obj",
"snub square antiprism.obj",
"sphenocorona.obj",
"sphenomegacorona.obj",
"square antiprism.obj",
"square cupola.obj",
"square gyrobicupola.obj",
"square orthobicupola.obj",
"square pyramid.obj",
"tetrahedron.obj",
"triangular bipyramid.obj",
"triangular cupola.obj",
"triangular hebesphenorotunda.obj",
"triangular orthobicupola.obj",
"triangular prism.obj",
"triaugmented dodecahedron.obj",
"triaugmented hexagonal prism.obj",
"triaugmented triangular prism.obj",
"triaugmented truncated dodecahedron.obj",
"tridiminished icosahedron.obj",
"tridiminished rhombicosidodecahedron.obj",
"trigyrate rhombicosidodecahedron.obj",
"truncated cube.obj",
"truncated cuboctahedron.obj",
"truncated dodecahedron.obj",
"truncated icosahedron.obj",
"truncated icosidodecahedron.obj",
"truncated octahedron.obj",
"truncated tetrahedron.obj"
]
